
# This is a basic workflow to help you get started with Actions

name: Test-Input
on:

  workflow_dispatch:
    inputs:
      releaseCanditateVersion:
        description: 'Name of version (ie vX.Y.Z)'
        required: true
      commitId:
        description: 'Commit ID'
        required: true

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "run-shell-command"
  run-shell-command:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
